### PR TITLE
2023.5.0 fix

### PR DESCRIPTION
**Pull request by fsobolev**
* Build using `hotfix` branch of Denaro
* Unneeded files are removed, they are in Denaro's sources

### CODE REVIEW

**Comment by fsobolev** [comment]
bot, build

**Comment by nlogozzo** [comment]
bot, build org.nickvision.tubeconverter

**Comment by nlogozzo** [comment]
bot, build org.nickvision.money

**Comment by nlogozzo** [comment]
bot, build org.nickvision.money

**Pull request merged**
